### ISSUE TITLE
Crash on Raspberry Pi 3b+ with Raspberry Pi OS

### ISSUE THREAD

**Issue by ingel81** [L3tum/HardwareInformation#28]
Thanks for this nice library!

I recently migrated my project from .NET Core 3.1 to .NET 5. Also updated the version of your lib from 4.0.3 to 5. Working nicely on Windows, but when calling it like this on an Raspberry Pi 3b+ with a current Raspberry Pi OS (previously called Raspbian)...

```csharp
var machineInformation = MachineInformationGatherer.GatherInformation(logger: mInfoLogger);
```

there is an internal NullPointerException in the method GatherInformation(). This has worked on the PI before, but was also an older OS (might still could have been raspbian at that point).

I provided an ILogger<> to your method. I'll paste the relevant output of my log-system below. Maybe this could help:

```csharp
Feb 10 12:57:43 pi: COR [10.02. 12:57:43.961] WRN HardwareInformation.MachineInformation: Vulkan shared library is not available.
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.062] ERR HardwareInformation.MachineInformation: Encountered while parsing BIOSVersion
Feb 10 12:57:44 pi: System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/dmi/id/bios_version'.
Feb 10 12:57:44 pi:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Feb 10 12:57:44 pi:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Feb 10 12:57:44 pi:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
Feb 10 12:57:44 pi:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
Feb 10 12:57:44 pi:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Feb 10 12:57:44 pi:    at System.IO.File.ReadAllText(String path)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetMainboardInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.123] ERR HardwareInformation.MachineInformation: Encountered while parsing BIOSVendor
Feb 10 12:57:44 pi: System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/dmi/id/bios_vendor'.
Feb 10 12:57:44 pi:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Feb 10 12:57:44 pi:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Feb 10 12:57:44 pi:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
Feb 10 12:57:44 pi:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
Feb 10 12:57:44 pi:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Feb 10 12:57:44 pi:    at System.IO.File.ReadAllText(String path)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetMainboardInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.127] ERR HardwareInformation.MachineInformation: Encountered while parsing BoardName
Feb 10 12:57:44 pi: System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/dmi/id/board_name'.
Feb 10 12:57:44 pi:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Feb 10 12:57:44 pi:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Feb 10 12:57:44 pi:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
Feb 10 12:57:44 pi:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
Feb 10 12:57:44 pi:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Feb 10 12:57:44 pi:    at System.IO.File.ReadAllText(String path)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetMainboardInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.132] ERR HardwareInformation.MachineInformation: Encountered while parsing BoardVendor
Feb 10 12:57:44 pi: System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/dmi/id/board_vendor'.
Feb 10 12:57:44 pi:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Feb 10 12:57:44 pi:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Feb 10 12:57:44 pi:    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
Feb 10 12:57:44 pi:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
Feb 10 12:57:44 pi:    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
Feb 10 12:57:44 pi:    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
Feb 10 12:57:44 pi:    at System.IO.File.ReadAllText(String path)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetMainboardInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.182] ERR HardwareInformation.MachineInformation: Encountered while parsing disk info
Feb 10 12:57:44 pi: System.ComponentModel.Win32Exception (2): No such file or directory
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.Start()
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
Feb 10 12:57:44 pi:    at HardwareInformation.Util.StartProcess(String cmd, String args)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetDiskInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.220] ERR HardwareInformation.MachineInformation: Encountered while parsing RAM
Feb 10 12:57:44 pi: System.ComponentModel.Win32Exception (2): No such file or directory
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.Start()
Feb 10 12:57:44 pi:    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
Feb 10 12:57:44 pi:    at HardwareInformation.Util.StartProcess(String cmd, String args)
Feb 10 12:57:44 pi:    at HardwareInformation.Providers.LinuxInformationProvider.GetRAMInformation(MachineInformation& information)
Feb 10 12:57:44 pi: COR [10.02. 12:57:44.362] WRN Elc.MonitoringService: Error reading machine informations
Feb 10 12:57:44 pi: System.NullReferenceException: Object reference not set to an instance of an object.
Feb 10 12:57:44 pi:    at HardwareInformation.MachineInformationGatherer.GatherInformation(Boolean skipClockspeedTest, Boolean invalidateCache, ILogger`1 logger)
```

**Comment by L3tum** [comment]
Hey, thanks for the detailed report! It's always nice to see something like this :)

I'll see if I can fix this over the weekend. I'll try to clean up the logging a bit as well^^
